# Generated by Django 6.0.3 on 2026-07-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
