"""
Django settings for temp1 project.
Generated by 'django-admin startproject' using Django 6.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# --- Core Imports ---
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# --- Helper Functions for Environment-based Settings ---
# These functions help make the settings flexible for both development and production.

# A helper to convert environment variables like 'true', '1', 'yes' into a Python boolean.
def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}

# A helper to build the list of allowed hosts. It starts with defaults and adds
# the PythonAnywhere domain if it exists, making deployment easier.
def get_allowed_hosts():
    hosts = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if pa_domain := os.getenv('PYTHONANYWHERE_DOMAIN'):
        hosts.append(pa_domain)
    return [host.strip() for host in hosts if host.strip()]

# A custom function to load secret keys and other settings from a `.env` file.
# This allows you to keep secrets out of your code, which is a major security best practice.
def load_local_env(path):
    """Load development-only values from .env without adding a dependency."""
    # Only try to read the file if it actually exists and is a file (not a directory).
    if not path.is_file():
        return
    # Read the file line by line.
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        # Ignore empty lines and lines that are comments (start with #).
        if not line or line.startswith('#') or '=' not in line:
            continue
        # Split the line into a key and a value.
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # Set the environment variable, but only if it's not already set.
        os.environ.setdefault(key, value)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file in the project root.
# This is the directory that contains the manage.py file.
load_local_env(BASE_DIR / '.env')

# Production values come from the host environment, never source control.
DEBUG = env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-development-only-change-before-deploy')
if not DEBUG and (SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured('Set a strong DJANGO_SECRET_KEY before deploying NexCart.')

ALLOWED_HOSTS = get_allowed_hosts()

# Add the PythonAnywhere host to trusted origins for CSRF protection.
def get_csrf_trusted_origins():
    origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if pa_domain := os.getenv('PYTHONANYWHERE_DOMAIN'):
        origins.append(f"https://{pa_domain}")
    return [origin.strip() for origin in origins if origin.strip()]
CSRF_TRUSTED_ORIGINS = get_csrf_trusted_origins()


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
]

# MIDDLEWARE is a framework of hooks into Django's request/response processing.
# The order is important. For example, SecurityMiddleware should come first.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The root URL configuration file for the project.
ROOT_URLCONF = 'temp1.urls'

# --- Template Configuration ---
# This tells Django where to find your HTML templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# The entry point for WSGI-compatible web servers to serve your project.
WSGI_APPLICATION = 'temp1.wsgi.application'


# --- Database Configuration ---

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
# Using BigAutoField is the modern standard to prevent primary key exhaustion.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The `dj_database_url` package allows you to configure your database from a single URL string,
# which is perfect for production environments where the database URL is provided as an environment variable.
import dj_database_url

# Determine if we are using SQLite by checking if DATABASE_URL is set.
using_sqlite = 'DATABASE_URL' not in os.environ

DATABASES = {
    'default': dj_database_url.config(
        # If DATABASE_URL is not set in the environment, it falls back to using a local SQLite file.
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        # SSL is required for most cloud databases but not for SQLite. This logic handles that automatically.
        ssl_require=False if using_sqlite else env_bool('DJANGO_DB_SSL', not DEBUG)
    )
}


# --- Password Validation ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internationalization & Localization ---
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- Static & Media File Configuration ---
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL is the URL prefix for static files (CSS, JavaScript, Images).
STATIC_URL = 'static/'
# STATICFILES_DIRS tells Django where to find your project's static files, in addition to each app's 'static' directory.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# STATIC_ROOT is the single directory where `collectstatic` will gather all static files for production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use WhiteNoise for static files in production, but not for local development.
# WhiteNoise allows your web app to serve its own static files efficiently without needing a separate web server like Nginx.
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# For user-uploaded files (MEDIA), we use Cloudinary in production.
# This offloads file storage to a dedicated service, which is more scalable and secure.
if not DEBUG:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# MEDIA_URL is the URL prefix for user-uploaded files.
MEDIA_URL = '/media/'
# MEDIA_ROOT is the local directory where media files are stored during development.
MEDIA_ROOT = BASE_DIR / 'media'

# --- Email Configuration ---
# These settings configure how Django sends emails (e.g., for verification codes).
# They are loaded from environment variables for security.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in {'1', 'true', 'yes'}
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', os.getenv('GMAIL_ADDRESS', ''))
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', os.getenv('GMAIL_APP_PASSWORD', ''))
# The default "from" address for emails sent by the site.
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@nexcart.local')

# --- Third-Party Service Configuration ---

# Cloudinary credentials, loaded from environment variables.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# --- Production Security Headers ---
# These settings enhance security when running in production (DEBUG=False).

# Hosts such as Render terminate HTTPS before passing requests to Django.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0

# --- Authentication & Authorization ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
